apps/backend/urls.py
from django.urls import path
from apps.backend.views import activate
from . import views

app_name = "backend"

urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('users/list', views.Users_List.as_view(), name='users_list'),
    path('users/create', views.Users_Create.as_view(), name='users_create'),
    path('users/update/<pk>', views.Users_Update.as_view(), name='users_update'),
    path('users/change-password', views.change_password, name='users_change_password'),
    path('users/delete/<pk>', views.Users_Delete.as_view(), name='users_delete'),

    path('clients/list', views.Clients_List.as_view(), name='clients_list'),
    path('clients/csv', views.clients_to_csv, name='clients_to_csv'),
    path('clients/export', views.client_to_csv_export, name='client_to_csv_export'),
    path('clients/create', views.Clients_Create.as_view(), name='clients_create'),
    path('clients/update/<pk>', views.Clients_Update.as_view(), name='clients_update'),
    path('clients/delete/<pk>', views.Clients_Delete.as_view(), name='clients_delete'),

    path('file/list', views.FilesPDF_List.as_view(), name='file_list'),
]

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from apps.backend.views import register

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    from dynamic_preferences.registries import global_preferences_registry
    global_preferences = global_preferences_registry.manager()
    admin_title = global_preferences['app__app_name']
else:
    admin_title = 'defaul'

admin.site.site_header = admin_title
admin.site.index_title = admin_title
admin.site.site_title = admin_title

handler500 = 'apps.frontend.views.custom_error_view'
handler404 = 'apps.frontend.views.custom_page_not_found_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('apps.backend.urls')),
    path('register/', register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.frontend.urls'))
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('preferences/', include('dynamic_preferences.urls'))
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

templates/backend/default/inc/_footer.html
{% load i18n %}
<footer class="main-footer">
    <strong>Copyright &copy; {% now "Y" %} {{ app_name }}&nbsp;</strong> {% trans "All rights reserved" %}
</footer>

templates/backend/default/inc/_navbar_links.html
{% load i18n %}

<ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
    <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-user"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
            <a class="dropdown-item dropdown-footer">{% trans "hi"|title %}, {{ request.user.get_name }}</a>
            <a href="{% url 'backend:users_change_password' %}" class="dropdown-item dropdown-footer">{% trans "change password"|title %}</a>
            {% comment %}
                <a class="dropdown-item dropdown-footer">{% trans "edit profile"|title %}</a>
            {% endcomment %}
            <a href="{% url 'logout' %}" class="dropdown-item dropdown-footer">{% trans "Log out"|title %}</a>
        </div>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
            <i class="fas fa-th-large"></i>
        </a>
    </li>
</ul>

templates/backend/default/inc/_navbar_menu.html
{% load i18n %}

<div class="collapse navbar-collapse order-3" id="navbarCollapse">
<!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a href="{% url 'backend:home' %}" class="nav-link">{% trans "dashboard"|title %}</a>
        </li>
        {% if request.user.is_staff or request.user.is_superuser %}
            <li class="nav-item dropdown">
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">{% trans "users"|title %}</a>
                <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow" style="left: 0px; right: inherit;">
                    <li><a href="{% url 'backend:users_create' %}" class="dropdown-item">{% trans "create user"|capfirst %}</a></li>
                    <li><a href="{% url 'backend:users_list' %}" class="dropdown-item">{% trans "user list"|capfirst %}</a></li>
                </ul>
            </li>
        {% endif %}
        <li class="nav-item dropdown">
            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">{% trans "clients"|title %}</a>
            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow" style="left: 0px; right: inherit;">
                <li><a href="{% url 'backend:clients_create' %}" class="dropdown-item">{% trans "create client"|capfirst %}</a></li>
                <li><a href="{% url 'backend:clients_list' %}" class="dropdown-item">{% trans "client list"|capfirst %}</a></li>
            </ul>
        </li>
        <li class="nav-item">
            <a href="{% url 'backend:file_list' %}" class="nav-link">{% trans "datasheet"|title %}</a>
        </li>
    </ul>
    <!-- SEARCH FORM -->
    <form class="form-inline ml-0 ml-md-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="{% trans 'search'|title %}" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>
</div>