apps/backend/urls.py
from django.urls import path
from apps.backend.views import activate
from . import views

app_name = "backend"

urlpatterns = [
    path('', views.home.as_view(), name='home'),
    path('users/list', views.Users_List.as_view(), name='users_list'),
    path('users/create', views.Users_Create.as_view(), name='users_create'),
    path('users/update/<pk>', views.Users_Update.as_view(), name='users_update'),
    path('users/change-password', views.change_password, name='users_change_password'),
    path('users/delete/<pk>', views.Users_Delete.as_view(), name='users_delete'),

    path('clients/list', views.Clients_List.as_view(), name='clients_list'),
    path('clients/csv', views.clients_to_csv, name='clients_to_csv'),
    path('clients/export', views.client_to_csv_export, name='client_to_csv_export'),
    path('clients/create', views.Clients_Create.as_view(), name='clients_create'),
    path('clients/update/<pk>', views.Clients_Update.as_view(), name='clients_update'),
    path('clients/delete/<pk>', views.Clients_Delete.as_view(), name='clients_delete'),

    path('file/list', views.FilesPDF_List.as_view(), name='file_list'),
]

core/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from apps.backend.views import register

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    from dynamic_preferences.registries import global_preferences_registry
    global_preferences = global_preferences_registry.manager()
    admin_title = global_preferences['app__app_name']
else:
    admin_title = 'defaul'

admin.site.site_header = admin_title
admin.site.index_title = admin_title
admin.site.site_title = admin_title

handler500 = 'apps.frontend.views.custom_error_view'
handler404 = 'apps.frontend.views.custom_page_not_found_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('backend/', include('apps.backend.urls')),
    path('register/', register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.frontend.urls'))
]

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [path('rosetta/', include('rosetta.urls'))]

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('preferences/', include('dynamic_preferences.urls'))
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT,
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

apps/backend/views/client.py
import csv
import copy

from django.utils import timezone
from django.conf import settings
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.utils.translation import gettext as _
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from ..models import Client
from ..forms import ClientForm

if 'dynamic_preferences' in settings.INSTALLED_APPS:
    from dynamic_preferences.registries import global_preferences_registry
    global_preferences = global_preferences_registry.manager()
    theme_backend = global_preferences['app__app_theme_backend']
else:
    theme_backend = 'default'

class Clients_List(ListView):
    queryset = Client.objects.all()
    template_name = f'backend/{theme_backend}/clients/list.html'
    context_object_name = 'clients'

    def get_queryset(self):
        queryset = super().get_queryset()
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            queryset = queryset.filter(agent=self.request.user)
        return queryset

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class Clients_Create(CreateView):
    model = Client
    form_class  = ClientForm
    template_name = f'backend/{theme_backend}/clients/create.html'

    def get_initial(self):
        initial = super(Clients_Create, self).get_initial()
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            initial['agent'] = self.request.user
        initial['created_on'] = timezone.now().date()
        return initial

    def form_valid(self, form):
        name_business = form.cleaned_data['name']
        messages.success(self.request, f'you have successfully created the client: {name_business}')
        return super().form_valid(form)

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_success_url(self):
        return reverse('backend:clients_list')


class Clients_Delete(DeleteView):
    model=Client
    template_name=f'backend/{theme_backend}/clients/delete.html'
    success_url=reverse_lazy("backend:clients_list")

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

class Clients_Update(UpdateView):
    model = Client
    form_class  = ClientForm
    template_name = f'backend/{theme_backend}/clients/update.html'

    def test_func(self):
        if not self.request.user.is_staff and not self.request.user.is_superuser:
            obj = self.get_object()
            return obj.agent == self.request.user
        else:
            return True

    def form_valid(self, form):
        name_business = form.cleaned_data['name']
        messages.success(self.request, f'you have successfully updated the client: {name_business}')
        return super().form_valid(form)

    def get_success_url(self):
        if self.request.GET.get('continue_editing'):
            return reverse_lazy('backend:clients_update', args=[self.object.pk])
        else:
            return reverse('backend:clients_list')

@user_passes_test(lambda u: u.is_staff)
def clients_to_csv(request):
    queryset = Client.objects.all()
    filename = "clients.csv"

    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    writer = csv.writer(
        response,
        delimiter=';',
        quotechar='"',
        quoting=csv.QUOTE_MINIMAL)
    fields = Client.get_fields()
    writer.writerow(fields)

    for obj in queryset:
        row = [getattr(obj, field) for field in fields]
        writer.writerow(row)

    return response


@user_passes_test(lambda u: u.is_staff)
def client_to_csv_export(request):
    queryset = Client.objects.all()
    filename = "export_new_clients.csv"
    client_list = []
    BASE_CLIENT = {
        'POSALIAS':'',
        'CODPOS':'',
        'PROVIFISCAL':'',
        'RUTA':'',
        'ZONA':'',
        'CODMUNICIPIO':'',
        'CODMUNICIPIOFISCAL':'',
        'CODPAIS':'',
        'DTOPOS':'',
        'DTOFISCAL':'',
        'CODPROVI':'',
        'CODREP':'',
        'COMENTARIO':'',
        'DIRPOS':'',
        'DIRPOS1':'',
        'DIRPOS2':'',
        'DIRFISCAL':'',
        'E_MAIL':'',
        'EMAILFISCAL':'',
        'E_MAIL_PUBLI':'',
        'ENVIARDOC':'',
        'ESCALERA':'',
        'ESCALERAFISCAL':'',
        'EXTENSIONFISCAL':'',
        'FAXPOS':'',
        'FAXFISCAL':'',
        'FECALTA_ORG':'',
        'FECALTA':'',
        'AP_ID':'',
        'IDORG':'',
        'LINKEDIN':'',
        'SKYPE':'',
        'TWITTER':'',
        'MODIFICADO':'',
        'MOTIVOBLOQUEO':'',
        'MOTIVOBLOQUEO_ORG':'',
        'MUNICIPIO':'',
        'MUNICIPIOFISCAL':'',
        'NIFPOS':'',
        'ORDENRUTA':'',
        'NVIA':'',
        'RAZON':'',
        'NVIAFISCAL':'',
        'OBSERVACIONES':'',
        'OBSPOS':'',
        'OBSOLETO':'',
        'NOMPOS':'',
        'PAGINAWEB':'',
        'PAISFISCAL':'',
        'PISO':'',
        'PISOFISCAL':'',
        'POBPOS':'',
        'POBFISCAL':'',
        'PUERTA':'',
        'PUERTAFISCAL':'',
        'NOMFISCAL':'',
        'REFERENCIA':'',
        'TELPOS':'',
        'TELPOS2':'',
        'TELEFONOFISCAL':'',
        'TELEFONO2FISCAL':'',
        'TIPODOCNIF':'',
        'TIPOIMAGEN':'',
        'TIPONUMERO':'',
        'TIPONUMEROFISCAL':'',
        'ULTFECMOD':'',
        'VIA':'',
        'VIAFISCAL':'',
        'VIAPUBLICAFISCAL':''
    }
    for client in queryset:
        new_client = copy.deepcopy(BASE_CLIENT)
        new_client['FECALTA_ORG'] = client.created_on.strftime("%d/%m/%Y")
        new_client['FECALTA'] = client.created_on.strftime("%d/%m/%Y")
        if client.name:
            new_client['POSALIAS'] = client.name
            new_client['RAZON'] = client.name
            new_client['NOMPOS'] = client.name
        if client.province:
            new_client['POBPOS'] = 'ES'
            new_client['POBPOS'] = client.province.name
        if client.zipcode:
            new_client['DTOPOS'] = client.zipcode
            new_client['DTOFISCAL'] = client.zipcode
        if client.email:
            new_client['E_MAIL'] = client.email
        if client.comment:
            new_client['OBSERVACIONES'] = client.comment
        if client.web:
            new_client['PAGINAWEB'] = client.web
        if client.telephone:
            new_client['TELPOS2'] = client.telephone
        if client.address:
            new_client['VIAFISCAL'] = client.address
            new_client['DIRPOS'] = client.address
        client_list.append(new_client)



    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="{filename}"'
    writer = csv.DictWriter(
        response,
        fieldnames=BASE_CLIENT.keys(),
        delimiter=';',
        quotechar='"',
        quoting=csv.QUOTE_MINIMAL
    )
    writer.writeheader()
    for row in client_list:
        writer.writerow(row)

    return response

templates/backend/default/clients/change_password.html
{% extends "../layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "dashboard" %}</a></li>
    <li class="breadcrumb-item">{% trans "change password" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="{% trans 'save' %}" class="btn btn-block btn-primary">
    </form>
{% endblock content %}

templates/backend/default/clients/create.html
{% extends "../layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "dashboard" %}</a></li>
    <li class="breadcrumb-item">{% trans "create client" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {{ form.business|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.agent|as_crispy_field }}
            </div>
        </div>
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">{% trans "client registration"|title %}</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        {{ form.new_client|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.created_on|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.cif|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.address|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.province|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.zipcode|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.web|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.contact_person|as_crispy_field }}
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.person_position|as_crispy_field }}
                        {{ form.telephone|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-title">{% trans "Activity"|title %}:</h3><br><br>
                        {{ form.a_engineering|as_crispy_field }}
                        {{ form.a_meter|as_crispy_field }}
                        {{ form.a_distributor|as_crispy_field }}
                        {{ form.a_installer|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-title">{% trans "Interest"|title %}:</h3><br><br>
                        {{ form.i_storage|as_crispy_field }}
                        {{ form.i_investor|as_crispy_field }}
                        {{ form.i_charger|as_crispy_field }}
                        {{ form.i_panels|as_crispy_field }}
                        {{ form.i_others|as_crispy_field }}
                    </div>
                    <div class="col-md-12" id="section-buttons">
                        {{ form.interest|as_crispy_field }}
                        {{ form.comment|as_crispy_field }}
                        <input type="submit" value="{% trans 'save'|upper %}" class="btn btn-success button-mobile">
                        <a href="backend:clients_list" class="btn btn-default button-mobile">{% trans "back to the list"|upper %}</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

templates/backend/default/clients/delete.html
{% extends "../layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "dashboard" %}</a></li>
    <li class="breadcrumb-item">{% trans "delete client" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>{% blocktrans with object=object %}Are you sure you want to delete "{{ object }}"?{% endblocktrans %}</p>
        <input type="submit" value="Confirm" class="btn btn-danger">
        <a href="{% url 'backend:users_list' %}" class="btn btn-default">{% trans "cancel"|title %}</a>
    </form>
{% endblock content %}

templates/backend/default/clients/list.html
{% extends "../layout.html" %}

{% load i18n %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/rowReorder.dataTables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.dataTables.min.css' %}">
{% endblock css %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "dashboard" %}</a></li>
    <li class="breadcrumb-item">{% trans "client list" %}</li>
{% endblock navigator %}

{% block content %}
    {% if request.user.is_staff or request.user.is_superuser %}
        <a href="{% url 'backend:clients_to_csv' %}" class="btn btn-info">{% trans "Export datas to CSV" %}</a>
        <a href="{% url 'backend:client_to_csv_export' %}" class="btn btn-success">{% trans "Export clients to CSV" %}</a>
    <hr>
    {% endif %}
    <table id="table_id" class="display">
        <thead>
            <tr>
                <th>{% trans "name"|capfirst %}</th>
                <th>{% trans "agent"|capfirst %}</th>
                <th>{% trans "telephone"|capfirst %}</th>
                <th>{% trans "email"|capfirst %}</th>
                <th>{% trans "options"|capfirst %}</th>
            </tr>
        </thead>
        <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.name }}</td>
                    <td>{{ client.agent.get_name|title }}</td>
                    <td>
                        {% if client.telephone %}
                            {{ client.telephone }}
                        {% else %}
                            {% trans "no data" %}
                        {% endif %}
                    </td>
                    <td>{{ client.email }}</td>
                    <td>
                        <a href="{% url 'backend:clients_update' client.pk %}" class="btn btn-default" title="{% trans 'edit' %}"><i class="fas fa-edit"></i></a>
                        {% if request.user.is_staff or request.user.is_superuser %}
                            <a href="{% url 'backend:clients_delete' client.pk %}" class="btn btn-danger" title="{% trans 'delete' %}"><i class="fas fa-trash"></i></a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block js %}
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.rowReorder.min.js' %}"></script>
    <script src="{% static 'js/dataTables.responsive.min.js' %}"></script>
    <script>
        $(document).ready( function () {
            $('#table_id').DataTable({
                {% if clients.count <= 11 %}
                    "searching":false,
                    "paging":false,
                {% else %}
                    "searching":true,
                    "paging":true,
                {% endif %}
                "responsive":true,
                "language": {
                    "lengthMenu": "{% trans 'Display _MENU_ records per page' %}",
                    "zeroRecords": "{% trans 'Nothing found - sorry'|capfirst %}",
                    "info": "{% trans 'Showing page _PAGE_ of _PAGES_' %}",
                    "infoEmpty": "{% trans 'no records available'|capfirst %}",
                    "infoFiltered": "{% trans '(filtered from _MAX_ total records)'|capfirst %}",
                    "search": "{% trans 'search'|capfirst %}",
                }
            });
        } );
    </script>
{% endblock js %}

templates/backend/default/clients/update.html
{% extends "../layout.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block navigator %}
    <li class="breadcrumb-item"><a href="{% url 'backend:home' %}">{% trans "dashboard" %}</a></li>
    <li class="breadcrumb-item">{% trans "update user" %}</li>
{% endblock navigator %}

{% block content %}
    <form method="post">{% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                {{ form.business|as_crispy_field }}
            </div>
            <div class="col-md-6">
                {{ form.agent|as_crispy_field }}
            </div>
        </div>
        <div class="card card-success">
            <div class="card-header">
                <h3 class="card-title">{% trans "client registration"|title %}</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        {{ form.new_client|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.created_on|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.cif|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.address|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.province|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.zipcode|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.web|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.contact_person|as_crispy_field }}
                        {{ form.email|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.person_position|as_crispy_field }}
                        {{ form.telephone|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-title">{% trans "Activity"|title %}:</h3><br><br>
                        {{ form.a_engineering|as_crispy_field }}
                        {{ form.a_meter|as_crispy_field }}
                        {{ form.a_distributor|as_crispy_field }}
                        {{ form.a_installer|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-title">{% trans "Interest"|title %}:</h3><br><br>
                        {{ form.i_storage|as_crispy_field }}
                        {{ form.i_investor|as_crispy_field }}
                        {{ form.i_charger|as_crispy_field }}
                        {{ form.i_panels|as_crispy_field }}
                        {{ form.i_others|as_crispy_field }}
                    </div>
                    <div class="col-md-12" id="section-buttons">
                        {{ form.interest|as_crispy_field }}
                        {{ form.comment|as_crispy_field }}
                        {% comment %}
                            <input type="submit" value="{% trans 'save' %}" class="btn btn-success">
                        {% endcomment %}
                        <button type="submit" name="submit" class="btn btn-success">{% trans "save"|upper %}</button>
                        <button type="submit" name="submit_continue" class="btn btn-secondary">{% trans "Save and continue editing"|upper %}</button>
                        <a href="{% url 'backend:clients_list' %}" class="btn btn-default button-mobile">{% trans "back to the list"|upper %}</a>
                        {% if request.user.is_staff or request.user.is_superuser %}
                            <a href="{% url 'backend:clients_delete' object.pk %}" class="btn btn-danger button-mobile" style="float:right">{% trans "delete" %}</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}


{% block js %}
<script>
    $(document).ready(function() {
        $('form').submit(function(event) {
            var button = $('form button[type="submit"]:focus');
            if (button.attr('name') == 'submit_continue') {
            this.action += '?continue_editing=1';
            }
        });
    });
</script>
{% endblock js %}